### ISSUE TITLE
Suggestion - smaller core library

### ISSUE THREAD

**Issue by jobjo** [LexiFi/lrt#1]
Great to see this library! I would suggest providing a smaller `Lrt` core. In particular I think `Lrt.Check` and `Lrt.Json` should rather be exposed as separate libraries. 

Also, for consistency I'd go with `typ_eq` or `type_eq.ml` instead of `TypeEq.ml`.

**Comment by nojb** [comment]
Hello, thanks for your message. And apologies for the delay in responding!

Some context about this library: it was written during an internship at LexiFi to replicate using ppx some of our internal techonologies which extend the OCaml compiler with runtime types. The result was quite satisfactory (this library), but we don't actually use it internally (we are very happy with our runtime types :)), and unfortunately we don't have the manpower at the moment to maintain it independently.

Regarding your suggestions, I think they are good, but as no-one is actively maintaining the library and there are no plans to release it in the near future it wouldn't make sense to accept PRs in this direction. Sorry about that!

**Comment by jobjo** [comment]
Thanks for the clarification, @nojb! Appreciate having this out in the public domain anyway. 

Also, noticed that it is very similar in spirit the [library](https://balez.github.io/generic/) described in [this paper](https://arxiv.org/pdf/1812.11665.pdf). At some point it'd be nice to have a robust (and type safe) alternative to ppx for type driven development.

**Comment by nojb** [comment]
> Also, noticed that it is very similar in spirit the [library](https://balez.github.io/generic/) described in [this paper](https://arxiv.org/pdf/1812.11665.pdf). At some point it'd be nice to have a robust (and type safe) alternative to ppx for type driven development.

Thanks for the pointer, I was not aware of it.

Still in the world of ppx, there is an interesting variation (making different choices, but surprisingly comprehensive)  at https://github.com/thierry-martinez/refl.

**Comment by jobjo** [comment]
> Still in the world of ppx, there is an interesting variation (making different choices, but surprisingly comprehensive) at https://github.com/thierry-martinez/refl.

Nice, did not know about `refl`. 

Note that the paper above is also not suggesting adding any extensions to OCaml but providing a similar ppx for deriving type safe representations.
