### ISSUE TITLE
Supported OCaml versions

### ISSUE THREAD

**Issue by joseferben** [LexiFi/lrt#3]
I tried to install `lrt` using OCaml 4.12.0 and I get following error:

```
#=== ERROR while compiling lrt.dev ============================================#
# context     2.0.8 | linux/x86_64 | ocaml-base-compiler.4.12.0 | pinned(git+ssh://git@github.com/LexiFi/lrt.git#038ff963)
# path        ~/03-src/game/_opam/.opam-switch/build/lrt.dev
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p lrt -j 15
# exit-code   1
# env-file    ~/.opam/log/lrt-866229-099be7.env
# output-file ~/.opam/log/lrt-866229-099be7.out
### output ###
# Error: This expression has type
# [...]
#            Ppxlib__Ast_pattern0.t
#        but an expression was expected of type
#          ((string Ppxlib__.Import.loc list * Ppxlib__.Import.pattern) option,
#           'b, 'c)
#          Ppxlib__.Ast_pattern0.t =
#            ((string Ppxlib__.Import.loc list * Ppxlib__.Import.pattern)
#             option, 'b, 'c)
#            Ppxlib__Ast_pattern0.t
#        Type Ppxlib__.Import.pattern = Astlib.Ast_414.Parsetree.pattern
#        is not compatible with type
#          string Ppxlib__.Import.loc list * Ppxlib__.Import.pattern 
```
I suppose my version of OCaml that is too recent. Are there any plans to update? What is the OCaml version you are using?

Also the instruction in the README.md does not work, for me `opam pin add lrt git@github.com:LexiFi/lrt.git` did the trick.

**Comment by nojb** [comment]
This code was an intern project (see https://watch.ocaml.org/videos/watch/cc7e3242-0bef-448a-aa13-8827bba933e3), and is not actively used inside LexiFi; and so it is not actively maintained. But I will try to take a look later and see if the code is easy to fix.

**Comment by joseferben** [comment]
Okay thanks for the info!

I managed to get it working with `ppxlib.0.24.0` and 
```
--- a/lib/dune
+++ b/lib/dune
@@ -4,7 +4,7 @@
  (inline_tests)
  (libraries stdlib-shims landmarks)
  (preprocess
-  (pps ppx_expect lrt.deriving landmarks.ppx)))
+  (pps ppx_expect lrt.deriving landmarks-ppx)))
 
 (rule
  (targets variant_lexer.ml)
```

**Comment by joseferben** [comment]
May I ask why you are not using it anymore? Do you have a different runtime type solution or you don't use runtime types at all?

**Comment by nojb** [comment]
> May I ask why you are not using it anymore? Do you have a different runtime type solution or you don't use runtime types at all?

At LexiFi we maintain a fork of the compiler that supports runtime types natively. All our technology is based on this feature. The idea behind this project was to see how much of that could be replicated using PPX, but we never really considered switching to it because the PPX implementation lacks the integration with the typechecker which is partly what makes our "native" support for runtime types so handy.

**Comment by joseferben** [comment]
Thank you very much for the clarification. I hope one day something like this could land upstream!
